Huge merge
chwarr/bond pull request #1
Opened 2017-05-10 00:40 UTC by lalo

This merge consists of:
- gbc c++ command line changes (adds --grpc)
- sync codegen
- basic thread_pool implementation + unit tests
- bond_utils.h for serialization and deserialization integration with grpc
- sync helloworld example that runs as a test

There is also a code review on **codeflow**.

2017-05-10 19:11 UTC, chwarr requested changes

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/bond_utils.h
> +    *own_buffer = true;
Yes, this is correct. By setting this to true, we're telling gRPC to free the buffer by calling [`grpc_byte_buffer_destroy`](https://github.com/grpc/grpc/blob/ae95edb515c72a51655e4164f3e2a96e4e33677c/include/grpc%2B%2B/impl/codegen/call.h#L295-L310) when it's done sending.

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/bond_utils.h
> +        reinterpret_cast<const char*>(data.data()), data.length());
`data.content()` is what we want here, instead of casting `data.data()`.

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/bond_utils.h
> +    return Status(StatusCode::OK, "ok");
Minor: don't need the "ok" string here.

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/bond_utils.h
> +    //bond::Deserialize(cbreader, payload);
Can we delete this commented out code?

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/bond_utils.h
> +    // figure out ref counting for bytebuffer
Minor: prefix this with a TODO

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/bond_utils.h
> +    return Status(StatusCode::OK, "ok");
Minor: don't need "ok" string here either.

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +    //     This is default value.
Minor: the "This is default value." comment just repeats what the code says pretty clearly. I'd remove it.

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +    // Constructs thread pool with specified number of threads
Minor: "Constructs _a_ thread pool with _the_ specified..."

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +    std::list<boost::scoped_thread<boost::join_if_joinable>> m_threads;
The code doesn't appear to be making much use of the linked-list nature of `m_threads`. A `std::vector` looks fine here, unless performance testing shows otherwise. (We'll want to call `std::vector::reserve` before the `push_back` loop in the ctor, as we know exactly how many items we're going to push.)

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +    //
These members looks like they can and should be private.

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +    std::list<boost::scoped_thread<boost::join_if_joinable>> m_threads;
Minor: `_threads` and `_work` for members variables to follow the convention in the core bond headers for private member variables.

2017-05-10 19:11 UTC, chwarr commented on cpp/test/grpc/CMakeLists.txt
> +        # grpc_test_codegen)
Should this comment be removed? The target_link_libraries below sets up a dependency for us.

2017-05-10 19:11 UTC, chwarr commented on cpp/test/grpc/CMakeLists.txt
> +# add_dependencies(grpc_test_common grpc_test_codegen)
Remove this commented out code?

2017-05-10 19:11 UTC, chwarr commented on cpp/test/grpc/CMakeLists.txt
> +# add_bond_codegen (TARGET grpc_test_codegen grpc_test_common.bond GRPC)
Remove this commented out code?

2017-05-10 19:11 UTC, chwarr commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +namespace bond { namespace ext
There's a mismatch between the namespace here and the file path. Intentional?

2017-05-10 19:11 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +        UnitTestSuite suite(name.c_str());
The `name` local doesn't appear to be needed. Can we just use `UnitTestSuite suite("gRPC ThreadPool");`?

2017-05-10 19:11 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +        int sum = 0;
Can we be safe and use `std::atomic<int> sum` instead of doing this without any synchronization?

2017-05-10 19:11 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(300));
We need to use explicit synchronization here. Sleeping is a recipe for spurious test failures. We'll want to use something like a `condition_variable` to notify the main test thread that the work has finished.

2017-05-10 19:11 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +        bond::ext::thread_pool* threads = new bond::ext::thread_pool(2);
Minor: `std::unique_ptr<thread_pool> threads(new bond::ext::thread_pool(2))` is preferred.

And, then, instead of `delete threads`, call `threads.reset()`.

2017-05-10 19:11 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +        int sum = 0;
`std::atomic<int> sum(0)` will allow us to get rid of the mutex.

2017-05-10 19:11 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +        });
Consider the following instead:

```
auto increment = [&sum, &sum_mutex](){
            std::this_thread::sleep_for(std::chrono::milliseconds(100));
            std::lock_guard<std::mutex> lock(sum_mutex);
            sum++;
        };

threads->schedule(increment);
threads->schedule(increment);
threads->schedule(increment);
threads->schedule(increment);
```

2017-05-10 19:11 UTC, chwarr commented on examples/cpp/grpc-helloworld/helloworld.cpp
> +    std::string server_address("0.0.0.0:50051");
We should listen either on `127.0.0.1:50051` (or `[::1]:50051`) not `0.0.0.0` (which requires causes a firewall prompt on Windows).

2017-05-10 19:11 UTC, chwarr commented on examples/cpp/grpc-helloworld/helloworld.cpp
> +        GreeterClient greeter(grpc::CreateChannel("localhost:50051", grpc::InsecureChannelCredentials()));
We need to connect to the same address that we listened on (i.e., use the same string). For example, on my machine `localhost` resolves to ::1 then 127.0.0.1.

2017-05-10 19:11 UTC, chwarr commented on examples/cpp/grpc-helloworld/helloworld.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(200));
Is there a deterministic way to wait for the server to be alive?
(Do we need to do this at all?)

2017-05-10 19:11 UTC, chwarr commented on examples/cpp/grpc-helloworld/helloworld.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(300));
We need to wait for the reply. Possibly with a timeout to fail the test sooner than an hour, but we need to wait.

2017-05-10 19:11 UTC, chwarr commented on examples/cpp/grpc-helloworld/helloworld.cpp
> +        auto deadline = std::chrono::system_clock::now() + std::chrono::microseconds(1000);
Can we use `std::chrono::steady_clock` or `GPR_CLOCK_MONOTONIC` instead so we don't have to worry about the system clock going backward?

(Do we even need this shutdown?)

2017-05-10 19:11 UTC, chwarr commented on examples/cpp/grpc-helloworld/helloworld.cpp
> +        auto deadline = std::chrono::system_clock::now() + std::chrono::microseconds(1000);
This time is in microseconds, but the other delays are in milliseconds. Intentional?

2017-05-10 19:11 UTC, chwarr commented
When you address the comments, can you do it in fixup commits so I can diff what I just reviewed with the changes?

2017-05-10 20:42 UTC, chwarr commented on examples/cpp/grpc-helloworld/helloworld.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(300));
I think we can do all of this without using the thread pool. Just make all the client requests in `main()`. The server created by the builder has its own thread pool to handle dispatching requests.

2017-05-10 21:01 UTC, lalo commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +namespace bond { namespace ext
sort of, didn't feel it should be on the grpc namespace but left it in that path since the path is not set in stone yet

2017-05-10 21:22 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(300));
Here's a quick and dirty event-like synchronization primitive:

```
class event
{
public:
    explicit event(bool initialValue = false) :
        _m(),
        _cv(),
        _set(initialValue)
    {}

    void set()
    {
        setResetImpl(true);
    }

    void reset()
    {
        setResetImpl(false);
    }

    void wait()
    {
        std::unique_lock<std::mutex> lock(_m);
        return _cv.wait(lock, [this]() {return _set;});
    }

    template <typename Rep, typename Period>
    bool wait(std::chrono::duration<Rep, Period> timeout)
    {
        std::unique_lock<std::mutex> lock(_m);
        return _cv.wait_for(lock, timeout, [this]() {return _set;});
    }

private:
    std::mutex _m;
    std::condition_variable _cv;
    bool _set;

    event(const event&) = delete;
    event(event&&) = delete;
    event& operator=(const event&) = delete;
    event& operator=(event&&) = delete;

    void setResetImpl(bool value)
    {
        {
            std::lock_guard<std::mutex> lock(_m);
            _set = value;
        }

        _cv.notify_all();
    }
};
```

2017-05-11 00:13 UTC, chwarr commented on cpp/inc/bond/ext/grpc/bond_utils.h
> +    return Status(StatusCode::OK, "");
`return Status::OK;` if not that, then just `return Status(StatusCode::OK)`.

2017-05-11 00:13 UTC, chwarr commented on cpp/inc/bond/ext/grpc/bond_utils.h
>      std::memcpy(buff.get(), GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));
I pushed a commit that gets rid of the copy that `grpc_byte_buffer_reader_readall` was making.

2017-05-11 00:17 UTC, chwarr commented on cpp/inc/bond/ext/grpc/bond_utils.h
> +    return Status(StatusCode::OK, "");
Minor: `Status::OK` or `Status(StatusCode::OK)`. There's no need for the `""`.

2017-05-11 00:17 UTC, chwarr commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +namespace bond { namespace ext
Agreed that this isn't gRPC-specific. For now, let's just put it in bond/ext/thread_pool.h

2017-05-11 00:29 UTC, chwarr requested changes
We're pretty close.

2017-05-11 00:29 UTC, chwarr commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +#pragma once
Minor: copyright header

2017-05-11 00:29 UTC, chwarr commented on cpp/test/grpc/main.cpp
> +#define BOOST_TEST_NO_MAIN
Minor: copyright header

2017-05-11 00:29 UTC, chwarr commented on cpp/test/grpc/CMakeLists.txt
> +# To add a new unit test suite, call add_unit_test at the bottom of this file on
Minor: copyright header

2017-05-11 00:29 UTC, chwarr commented on cpp/test/grpc/test_utils_grpc.h
> +#include <chrono>
Minor: copyright header

2017-05-11 00:29 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +
Minor: copyright header

2017-05-11 00:29 UTC, chwarr commented on cpp/test/grpc/test_utils_grpc.h
> +class Event
Minor: prevailing style in Bond C++ is lower-case class names. (Prevailing, not universal. 😄)

2017-05-11 00:29 UTC, chwarr commented on examples/cpp/grpc-helloworld/helloworld.cpp
> +    std::string server_address("127.0.0.1:50051");
Minor: can be `const`

2017-05-11 00:29 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +        int sum = 0;
This has been changed to an `atomic<int>` in `FinishAllTasksAfterDelete` but not here. Intentional?

2017-05-11 00:29 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
> +        sum_event.wait(std::chrono::seconds(30));
If `sum_event.wait(...)` returns false, we should fail the test. Something like

```
bool waitResult = sum_event.wait(std::chrono::seconds(30));
UT_AssertIsTrue(waitResult); // test timed out -- if we can pass a message, pass that as the message
```

2017-05-11 00:57 UTC, lalo commented on cpp/test/grpc/thread_pool.cpp
> +        int sum = 0;
yes, did not change it since its not being exercised

2017-05-11 00:58 UTC, lalo commented on cpp/test/grpc/CMakeLists.txt
> +# To add a new unit test suite, call add_unit_test at the bottom of this file on
cmakelists usually dont have it so i skipped this one

2017-05-11 01:17 UTC, chwarr approved these changes

2017-05-11 01:34 UTC, closed without merging

2017-05-11 01:34 UTC, chwarr commented
Merged into the branch https://github.com/chwarr/bond/tree/chwarr/grpc%2B%2B