[C++ gRPC] Add static library and dll examples
chwarr/bond pull request #10
Opened 2017-05-22 17:52 UTC by chadwalters

Add examples demonstrating use of static libraries and dll examples for Bond-over-gRPC. Includes gbc changes to emit dll declspec attributes on <service>::NewStub() call.

2017-05-22 21:20 UTC, chadwalters commented
Updated to include some improvements to .travis.yml, reflecting changes in master branch.

2017-05-22 22:16 UTC, lalo requested changes

2017-05-22 22:16 UTC, lalo commented on .travis.yml
> +    - if [ "$FLAVOR" == "cpp-grpc" ]; then cmake -DBOND_SKIP_GBC_TESTS=TRUE -DBOND_SKIP_CORE_TESTS=TRUE -DBOND_ENABLE_COMM=FALSE ..; fi
don't we need an -DBOND_ENABLE_GRPC=TRUE, the default is false right?

2017-05-22 22:16 UTC, lalo commented on .travis.yml
> +    - if [ "$FLAVOR" == "cpp-core" ]; then cmake -DBOND_SKIP_GBC_TESTS=TRUE -DBOND_ENABLE_COME=FALSE -DBOND_ENABLE_GRPC=FALSE ..; fi
-DBOND_ENABLE_COME=FALSE should be -DBOND_ENABLE_`COMM`=FALSE

2017-05-22 22:16 UTC, lalo commented on examples/cpp/grpc/grpc_dll/using_grpc_dll.cpp
> +    // Exersize gRPC facilities
typo: exercise

2017-05-22 23:50 UTC, chadwalters commented on .travis.yml
> +    - if [ "$FLAVOR" == "cpp-grpc" ]; then cmake -DBOND_SKIP_GBC_TESTS=TRUE -DBOND_SKIP_CORE_TESTS=TRUE -DBOND_ENABLE_COMM=FALSE ..; fi
The default is TRUE.

2017-05-23 00:34 UTC, lalo commented on examples/cpp/grpc/grpc_dll/using_grpc_dll.cpp
> +    // Exercize gRPC facilities
nit: exercise

2017-05-23 00:36 UTC, chadwalters commented on examples/cpp/grpc/grpc_dll/using_grpc_dll.cpp
> +    // Exercize gRPC facilities
Lol

2017-05-23 18:17 UTC, lalo approved these changes

2017-05-24 05:51 UTC, chwarr commented
Merged into grpc++ in commit ceac8d748c1430ad936cdc93a1.

2017-05-24 05:51 UTC, closed without merging