Parameterize service thread pool impl
chwarr/bond pull request #11
Opened 2017-05-23 08:58 UTC by chwarr

2017-05-23 17:38 UTC, lalo requested changes

2017-05-23 17:38 UTC, lalo commented on cpp/inc/bond/ext/grpc/thread_pool.h
> +    /// @warning The scheduled callback must be exectured at some point in the
typo: executed

2017-05-23 17:38 UTC, lalo commented on cpp/inc/bond/ext/grpc/thread_pool.h
>          // If preferred # of threads is 0, use # of cpu cores.
misplaced comment

2017-05-23 17:38 UTC, lalo commented on cpp/test/grpc/thread_pool.cpp
>  #include <functional>
should this include thread_pool ?

2017-05-23 21:27 UTC, chwarr commented on cpp/test/grpc/thread_pool.cpp
>  #include <functional>
Already does, but a few system headers were missing. Fixed in commit 467ce0f.

2017-05-23 21:27 UTC, lalo approved these changes

2017-05-24 04:19 UTC, chwarr commented
Merged into grpc++ in commit 7bbc2c034cb2d534b16f4b2d0e9b22ac6a5682d1

2017-05-24 04:19 UTC, closed without merging