[c++ grpc] Switch from comm's message to bonded
chwarr/bond pull request #13
Opened 2017-05-23 09:24 UTC by chwarr

The use of bond::comm::message was just a placeholder. Its functionality
is not needed, so it has been replaced with just bond::bonded.

2017-05-23 16:30 UTC, lalo approved these changes

2017-05-23 17:11 UTC, lalo requested changes
Compat grpc test changes are missing :thinking:

2017-05-23 20:46 UTC, chwarr commented
Doh. I've fixed up the compat tests in commit  a5507e1. Please take another look.

2017-05-23 20:49 UTC, lalo approved these changes

2017-05-24 01:24 UTC, chwarr commented
Merged into grpc++ in commit c75cfeb.

2017-05-24 01:24 UTC, closed without merging