[c++ grpc] Add threadpool to client side
chwarr/bond pull request #15
Opened 2017-05-23 17:33 UTC by lalo

Also removes _grpc.cpp file

2017-05-23 22:33 UTC, chwarr requested changes

2017-05-23 22:33 UTC, chwarr commented on compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs
> +        proxyName :: String
I'm fine dropping the type annotation here. I put it on things like `methodNames` and `serviceMethodsWithIndex` as they have more complicated types.

2017-05-23 22:33 UTC, chwarr commented on compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs
> +    ::bond::ext::gRPC::detail::client_unary_call_data< #{request methodInput}, #{response methodResult}, TThreadPool >* calldata = new ::bond::ext::gRPC::detail::client_unary_call_data< #{request met
Can use auto here on the left-hand side to make the code simpler.

2017-05-23 22:33 UTC, chwarr commented on compiler/bond.cabal
> -                    Language.Bond.Codegen.Cpp.Grpc_cpp
Do we need to update the compiler.vcxproj files that C# uses?

2017-05-23 22:33 UTC, chwarr commented on compiler/tests/generated/generic_service_grpc.h
> +    class Client
Can we generate type aliases so that `Client` uses `bond::ext::thread_pool` by default?

2017-05-23 22:33 UTC, chwarr commented on cpp/test/compat/grpc/pingpong_client.cpp
> +    std::unique_ptr<bond::ext::thread_pool> threadPool(new bond::ext::thread_pool());
The thread pool can have automatic storage.

2017-05-23 22:33 UTC, chwarr commented on cpp/test/compat/grpc/pingpong_client.cpp
> +    std::unique_ptr<bond::ext::thread_pool> threadPool(new bond::ext::thread_pool());
Minor: prefer `new bond::ext::thread_pool` over `new bond::ext::thread_pool()` for invoking ctors with no arguments. (It avoids in some places weird parses.)

2017-05-23 22:33 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld.cpp
> +    std::unique_ptr<bond::ext::thread_pool> threadPool(new bond::ext::thread_pool());
Here as well, the thread pool can use automatic storage.

2017-05-23 22:34 UTC, lalo commented on compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs
> +        proxyName :: String
this needs to stay

2017-05-23 22:42 UTC, lalo commented on compiler/bond.cabal
> -                    Language.Bond.Codegen.Cpp.Grpc_cpp
yes

2017-05-23 23:09 UTC, chwarr commented on compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs
> +        proxyName :: String
✔️

2017-05-23 23:16 UTC, chwarr commented on compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs
> +#{declName}::#{proxyName}<TThreadPool>::#{proxyName}(const std::shared_ptr< ::grpc::ChannelInterface>& channel, std::shared_ptr< ::bond::ext::gRPC::io_manager> ioManager, TThreadPool* threadPool)
This needs to be marked as `inline`.

2017-05-23 23:16 UTC, chwarr commented on compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs
> +void #{declName}::#{proxyName}<TThreadPool>::Async#{methodName}(::grpc::ClientContext* context, const #{request methodInput}& request, std::function<void(const #{response methodResult}&, const ::grpc
These member functions need to be marked `inline`.

2017-05-23 23:16 UTC, chwarr commented on compiler/bond.cabal
> -                    Language.Bond.Codegen.Cpp.Grpc_cpp
✔️

2017-05-23 23:16 UTC, chwarr commented on compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs
> +    ::bond::ext::gRPC::detail::client_unary_call_data< #{request methodInput}, #{response methodResult}, TThreadPool >* calldata = new ::bond::ext::gRPC::detail::client_unary_call_data< #{request met
✔️

2017-05-23 23:16 UTC, chwarr commented on compiler/tests/generated/generic_service_grpc.h
> +    class Client
✔️

2017-05-23 23:16 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld.cpp
> +    std::unique_ptr<bond::ext::thread_pool> threadPool(new bond::ext::thread_pool());
✔️

2017-05-23 23:16 UTC, chwarr commented on cpp/test/compat/grpc/pingpong_client.cpp
> +    std::unique_ptr<bond::ext::thread_pool> threadPool(new bond::ext::thread_pool());
✔️

2017-05-23 23:16 UTC, chwarr commented on cpp/test/compat/grpc/pingpong_client.cpp
> +    std::unique_ptr<bond::ext::thread_pool> threadPool(new bond::ext::thread_pool());
✔️

2017-05-23 23:17 UTC, chwarr requested changes
Just some `inline` stuff.

2017-05-23 23:20 UTC, chwarr approved these changes
I'm in the middle of merging a bunch of the PRs. I'll merge this one too.

2017-05-24 04:19 UTC, chwarr commented
Merged into grpc++ in commit 26674d3943b9bba702b32489a7a71486c896a328.

2017-05-24 04:19 UTC, closed without merging