[c++ grpc] Add Bond async client
chwarr/bond pull request #5
Opened 2017-05-15 23:32 UTC by lalo

- update test
- helloworld_proxy.h will be codegened

comments:
- ignore Greeter2 in helloworld_proxy.h, temp to get around from some collision with the current codegen
- still have some open questions on what to do with the operators in the proxy class
- I have a redundant use of cq, as part of proxy class and as part of each request that is made see AsyncSayHello, I'm still working on how to simplify that.

2017-05-16 00:20 UTC, chwarr requested changes
The biggest thing I see is that there's no way to share a completion queue/cq_poller across multiple proxies.

2017-05-16 00:20 UTC, chwarr commented on cpp/inc/bond/ext/grpc/detail/client_call_data.h
> +    typedef std::function<void(TResponse)> CallbackType;
We need to pass the returned status to the callback too.

2017-05-16 00:20 UTC, chwarr commented on cpp/inc/bond/ext/grpc/detail/client_call_data.h
> +    void dispatch(grpc::ChannelInterface* channel, ::grpc::CompletionQueue* cq, grpc::RpcMethod method, grpc::ClientContext* context, TRequest request)
Minor: lines are long. Can we wrap them?

2017-05-16 00:20 UTC, chwarr commented on cpp/inc/bond/ext/grpc/detail/client_call_data.h
> +        responseReader->Finish(&_response, &_status, (void*)this);
When does `responseReader` get deleted?

2017-05-16 00:20 UTC, chwarr commented on cpp/inc/bond/ext/grpc/detail/client_call_data.h
> +    void dispatch(grpc::ChannelInterface* channel, ::grpc::CompletionQueue* cq, grpc::RpcMethod method, grpc::ClientContext* context, TRequest request)
The type of request should be `const TRequest&`, and ideally we wouldn't need to copy request ever. We just keep passing references down until we get to `SerializationTraits::Serialize`.

2017-05-16 00:20 UTC, chwarr commented on cpp/inc/bond/ext/grpc/proxy.h
> +        proxy(const proxy&) = delete;
These look like they shouldn't be commented out. They signal to the consuming programmer what operations we anticipated on this class.

2017-05-16 00:20 UTC, chwarr commented on cpp/inc/bond/ext/grpc/proxy.h
> +        proxy(std::unique_ptr<grpc::CompletionQueue> cq)
Hmmm... It should be possible for a bunch of proxies for different services even across different channels to share the same completion queue. A proxy should take a pointer/reference to a cq_poller. We may need to rejigger the abstractions to make this possible.

2017-05-16 00:20 UTC, chwarr commented on cpp/inc/bond/ext/grpc/proxy.h
> +
Minor: odd blank line

2017-05-16 00:20 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld.cpp
>          return 1;
We should print here that we timed out waiting for the correct response.

2017-05-17 23:58 UTC, chwarr requested changes
The proxy shutting down the `io_manager` that it only has shared ownership of needs to be addressed.

2017-05-17 23:58 UTC, chwarr commented on cpp/inc/bond/ext/grpc/proxy.h
> -#include <memory>
Minor: We still need `#include <memory>`

2017-05-17 23:58 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld.cpp
> +void printAndSet(event* print_event, bool* isCorrectResponse, const bond::comm::message< HelloReply>& response, const Status& status) {
Minor: line is long. Can we wrap?

2017-05-17 23:58 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld.cpp
> +    if(status.ok())
It looks like we don't set `*isCorrectResponse` when `!status.ok()`.

2017-05-17 23:58 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld.cpp
> +        if (message.compare(std::string("hello world")) == 0)
Minor: can simplify to `message.compare("hello world")`, IIRC.

2017-05-17 23:58 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld.cpp
> +    std::shared_ptr<io_manager> ioManager(new io_manager(std::move(cq_)));
Minor: `auto ioManaged = std::make_shared<io_manager>(std::move(cq_));`, or, if possible: `auto ioManaged = std::make_shared<io_manager>(new grpc::CompletionQueue);`

2017-05-17 23:58 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld.cpp
>          return 1;
✔️

2017-05-17 23:58 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld.cpp
> +    if (!waitResult)
Minor: can we surround these block with curly braces?

2017-05-17 23:58 UTC, chwarr commented on cpp/inc/bond/ext/grpc/proxy.h
> +        proxy(const proxy&) = delete;
✔️

2017-05-17 23:58 UTC, chwarr commented on cpp/inc/bond/ext/grpc/proxy.h
> +            _ioManager->shutdown();
This proxy doesn't exclusively own the `io_manager`, so it shouldn't shut it down. We'll need to figure out some other way to get the behavior we want (the ability to synchronously wait for the outstanding work initiated by this proxy to drain).

2017-05-17 23:58 UTC, chwarr commented on cpp/inc/bond/ext/grpc/detail/client_call_data.h
> +            , io_manager* ioManager
Minor: we don't wrap like this in the rest of the Bond code (Comm excepted). Can we switch to

```
void dispatch(grpc::ChannelInterface* channel,
    io_manager* ioManager,
    grpc::RpcMethod method,
...
```

2017-05-18 00:59 UTC, lalo commented on cpp/inc/bond/ext/grpc/proxy.h
> +            _ioManager->shutdown();
plus I'm not enforcing shutdown also from the dispatch() method

2017-05-18 01:43 UTC, chwarr commented on cpp/inc/bond/ext/grpc/proxy.h
> +            _ioManager->shutdown();
For the initial version of the gRPC++ extensions, let's just not have explicit per-proxy shutdown. If you want to fail all the inflight client calls, shutdown the `io_manager`. If you need to be able to do this per-proxy, create a unique `io_manager` for each proxy (with a limited thread count, likely). We can make this better later, after getting some feedback.

2017-05-18 23:01 UTC, chwarr requested changes

2017-05-18 23:01 UTC, chwarr commented on cpp/inc/bond/ext/grpc/proxy.h
> +    class proxy
You're right that this proxy is so thin that it doesn't really need to exist. (There are no sensible operations that one can perform against just a proxy.)

Options I see:

* move the interesting code from the generated `AsyncFoo` methods into a protected method (see below)
* get rid of the proxy class and just generate an `io_manager` member.

Possible protected member

```
// would be inside the class definition, but I'm using extern syntax for this example

template <typename TRequest, typename TResponse, typename Callback>
proxy::send_async(
    ::grpc::RpcMethod& method,
    ::grpc::ClientContext* context,
    const TRequest& request,
    Callback&& cb)
{
    typedef ::bond::ext::gRPC::detail::client_unary_call_data<::bond::comm::message<TRequest>, ::bond::comm::message<TResponse>> CallData;
    auto callData = new CallData(std::forward(cb));
    callData->dispatch(_channel.get(), _ioManager.get(), method, context, request);
}
```

2017-05-19 00:22 UTC, lalo commented on cpp/inc/bond/ext/grpc/proxy.h
> +    class proxy
I don't see a clear benefit in keeping the proxy, plus we've never had a proxy that is not codegen. I'll add the io_manager.

2017-05-19 00:58 UTC, chwarr approved these changes

2017-05-19 00:58 UTC, chwarr commented on examples/cpp/grpc/helloworld/helloworld_proxy.h
> +      ioManager_ = ioManager;
Minor: use the initializer list to set this. Also, remember to initialize things in the initializer list in the same order that they're declared.

2017-05-19 01:10 UTC, merged